---

##############################################################################
## Provision ceph
##############################################################################

- name: Check if cluster is openshift
  set_fact:
    is_openshift: "{{ q('k8s', cluster_info='version').0.openshift is defined }}"

- name: Set up security context constraints for OpenShift
  k8s:
    definition: '{{ lookup("file", "scc.yaml") }}'
  when: is_openshift

- name: Deploy CRDs and operator
  k8s:
    definition: '{{ lookup("template", "operator.yaml") }}'
  vars:
    rook_requires_privileged: '{{ is_openshift }}'

- name: Deploy cluster and storageclass
  k8s:
    definition: '{{ lookup("file", item) }}'
  loop:
    - cluster.yaml
    - storageclass.yaml

# TODO: add actual configuration options
