---

##############################################################################
## Provision ceph
##############################################################################

- name: Deploy
  k8s:
    definition: '{{ lookup("file", item) }}'
  loop:
    - operator.yaml
    - cluster.yaml
    - storageclass.yaml

# TODO: add actual configuration options
