---

##############################################################################
## Provision ceph
##############################################################################

- name: Deploy
  k8s:
    definition: '{{ lookup("file", item) }}'
  with_fileglob:
    - files/*

# TODO: add actual configuration options
